# Generated by Django 4.2.7 on 2023-12-04 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newdislikes',
            field=models.ManyToManyField(blank=True, related_name='newdisliked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='newlikes',
            field=models.ManyToManyField(blank=True, related_name='newliked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
