# Generated by Django 4.2.7 on 2023-12-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_followings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followings',
        ),
    ]
