# Generated by Django 4.2.7 on 2023-12-07 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0010_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
